hl.on("hyprland.start", function ()
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("eww open activate-linux")
    hl.exec_cmd("quickshell -d --path ~/.config/minerva_shell")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("~/.config/hypr/scripts_hypr/udev.sh")
    hl.exec_cmd("hyprpm reload -n")
end)
