hl.on("hyprland.start", function ()
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("eww open activate-linux")
    hl.exec_cmd("quickshell -d")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("~/.config/hypr/scripts_hypr/power_animations.sh")
end)
