hl.env("AQ_NO_MODIFIERS", 1)
hl.env("XCURSOR_SIZE",24)
hl.env("HYPRCURSOR_SIZE",24)
hl.env("QT_QPA_PLATFORMTHEME","qt6ct")
hl.env("XDG_MENU_PREFIX","arch-")
hl.env("MOZ_ENABLE_WAYLAND",1)
hl.env("XDG_CURRENT_DESKTOP","Hyprland")
hl.env("XDG_SESSION_TYPE","wayland")
hl.env("QML_IMPORT_PATH","/home/luisp/.config/quickshell")
