exec-once = swww-daemon
exec-once = clipse -listen
exec-once = hypridle
exec-once = kbuildsycoca6
exec-once = eww daemon
exec-once = eww open activate-linux
exec-once = quickshell -d
exec-once = systemctl --user start hyprpolkitagent
exec-once = whatsie
exec-once = pypr
