# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# windowrules
windowrule = match:class kitty, float on, size 800 400, center on
windowrule = match:class Spotify, opacity 0.85
windowrule = match:class Alacritty, float on, size 800 400, center on
windowrule = match:class clipse-gui, match:title Clipse GUI, float on, size 600 800, center on
windowrule = match:class chromium-browser, size 390 275, float on, pin on, move 1505 65
windowrule = match:title Picture-in-Picture, float on, size 450 250, pin on, move 1450 815
windowrule = match:title satty, float on, size 800 600, center on
windowrule = match:class DesktopEditors, center on
windowrule = match:title EverCal, float on, size 800 600, center on
windowrule = match:title HyprEmoji, rounding 20, border_color rgba(ffffffff), border_size 1, no_shadow on

# layer_rules
layerrule = match:namespace power-menu, animation fade
layerrule = match:namespace notificationcenter, blur off, ignore_alpha 1, order 1
layerrule = match:namespace selection, blur off, ignore_alpha 1
layerrule = match:namespace quickshell, blur off, ignore_alpha 1
layerrule = match:namespace wallpaper-picker, blur off, ignore_alpha 0.1, animation popin 80%
layerrule = match:namespace rofi, blur off
layerrule = ignore_alpha 0.1, match:namespace rofi
layerrule = match:class dolphin, blur on
layerrule = match:namespace rofi, animation popin 80%
layerrule = match:namespace quickshell, animation fade
layerrule = match:namespace launcher-dismiss, blur off, ignore_alpha 0.1
layerrule = match:namespace airdrop-dismiss, blur off, ignore_alpha 0.1
layerrule = match:namespace gtk-layer-shell, blur disable
layerrule = match:namespace gtk4-layer-shell, blur disable


#smart-gaps
workspace = w[tv1], gapsout:10, gapsin:5
workspace = f[1], gapsout:10, gapsin:5
windowrule = border_size 1, match:float 0, match:workspace w[tv1]
windowrule = rounding 5, match:float 0, match:workspace w[tv1]
windowrule = border_size 1, match:float 0, match:workspace f[1]
windowrule = rounding 5, match:float 0, match:workspace f[1]
