general {
    lock_cmd = qs --path ~/.config/minerva_shell ipc call shell lockscreen
}

listener {
    timeout = 400
    on-timeout = loginctl lock-session
}

listener {
    timeout = 550
    on-timeout = systemctl suspend
}
